<?php
/**
 * Created by PhpStorm.
 * User: mrdos
 * Date: 14.02.2017
 * Time: 15:00
 */
namespace  frontend\widgets;
use frontend\modules\cabinet\models\Advert;
use \yii\base\Widget;

class HotWidget extends Widget
{
    public function  run()
    {
        $model = Advert::find()->where('hot = 1')->limit(5)->all();

        return $this->render('hot', ['model' => $model]);
//        parent::run(); // TODO: Change the autogenerated stub
    }
}

?>
